version: '3.8'

services:
  # Node.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    env_file:
      - .env
    command: sh -c "npm run migration:run && npm run dev"
    networks:
      app_network:
    volumes: 
      - .:/app:z
      - /app/node_modules:z
    

  # postgres service
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      app_network:
    volumes:
      - .docker/postgres/db:/var/lib/postgresql/data:z

networks:
  app_network:

volumes:
  pgdata:
